version: '3.3'

services:
  dashboard-proxy:
    image: samirtalwar/overthefinishline.com-proxy
    environment:
      'SERVER_NAME': 'swarm.overthefinishline.com'
      'BACKEND': 'dashboard'
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    depends_on:
      - dashboard

  dashboard:
    image: samirtalwar/overthefinishline.com-dashboard
    entrypoint:
      - '/usr/local/bin/overthefinishline-dashboard-exe'
    env_file: production.env
    ports:
      - 80
    deploy:
      replicas: 2
      restart_policy:
        condition: any
