#!/usr/bin/env zsh

set -e

cd $(dirname $0)

done=false
trap 'done=true' SIGINT SIGTERM

function run {
    docker-compose up -d
}

function terminate {
    docker-compose down
}

while ! $done; do
    echo
    date
    run || true
    fswatch --one-event .built >/dev/null
done
terminate
