#!/usr/bin/env zsh

set -e

raw_test_file="$(mktemp).js"
test_file='elm-stuff/test.js'

elm-make --yes --output $raw_test_file test/Main.elm
sh ./elm-stuff/packages/laszlopandy/elm-console/1.1.1/elm-io.sh $raw_test_file $test_file
node $test_file
