#!/usr/bin/env zsh

set -e

cd $(dirname $0)

jar=server/target/dashboard-server.jar
config_path=development.env

pid=0
done=false

function run {
    env $(cat $config_path) java -jar $jar &
    pid=$!
}

function terminate {
    kill $pid || :
}

trap 'done=true' SIGINT SIGTERM

run
while ! $done; do
    fswatch --one-event --latency=5 $jar $config_path >/dev/null
    terminate
    run
done
terminate
