#!/usr/bin/env zsh

set -e

cd $(dirname $0)

NAME=overthefinishline-dashboard-server-exe

application_path=$(cd server && stack exec which $NAME)
config_path=development.env

pid=0
done=false

function run {
    env $(cat $config_path) $application_path &
    pid=$!
}

function terminate {
    kill $pid || :
}

trap 'done=true' SIGINT SIGTERM

run
while ! $done; do
    fswatch --one-event --latency=1 $application_path $config_path >/dev/null
    terminate
    run
done
terminate
